<doctype html>
<html>
<head>
	<title>new 1 test title</title>
	<meta charset="utf-8"/>
	<link rel="stylesheet" type="text/css" href="style.css"
	<style>
	</style>

</head>
<body>
	<h1>Test new1, a form in post method passing data to php file</h1>
	<form action="submit.php" method="POST" >
		<label>Name:   </label>
		<input type="text" name="name" placeholder="Name" >
		<br/> <br/>
		<label>Roll:    </label>
		<input type="text" name="roll" placeholder="ID" >
		<br/> <br/>
		<label>Department: </label>
		<input type="text" name="dept" placeholder="department name" >
		<br/> <br/>
		<label>Fee:      </label>
		<input type="text" name="fee" placeholder="amount">
		<br/><br/>
		
		<input type="submit" value="Submit">
		</form>
		
		<br/><br/><br/><br/>
		<a href="display.php">Click here to display</a>
		<br/><br/><br/>
<?php
	$hostname="localhost";
	$username="root";
	$password="";
	$dbname="testdb";
	$conn= new mysqli("$hostname", "$username", "$password", "$dbname");
	$sql="SELECT * FROM info";
	$result= $conn->query($sql);
?>
	<table border=1>
	<tr>
		<th>Name</th>
		<th>Roll</th>
		<th>Dept</th>
		<th>Fee</th>
		
	</tr>
	<?php
	while($row= $result->fetch_assoc()){
		
	
	?>
	<tr>
		<td> <?php echo $row["Name"]; ?> </td>
		<td> <?php echo $row["Roll"]; ?> </td>
		<td> <?php echo $row["Dept"]; ?> </td>
		<td> <?php echo $row["Name"]; ?> </td>
	
	<?php
	}
		$conn->close();
	?>	
	
</tr>
	</table>
	
	<br/><br/><br/>
	
	<h2 onclick="this.innerHTML = 'Text chanGeD!!!'">Click to change</h2><br/><br/><br/>
	<h3 onclick="changeText(this)"> Text change by event handler JS</h3>
	<script>
		function changeText(id){
			id.innerHTML="New text generated by event handler JS!!!";
		}
	</script>
	<br/><br/><br/>
	<button  onclick="buttonChange()">Button</button>
	<h4 id="btn"></h4>
	<script>
		function buttonChange(){
		
			document.getElementById("btn").innerHTML= "New button Text!!!";
		}
	</script>
	<br/><br/><br/>
	<button id="btn2" onclick="buttonChange2()">Button</button>
	<script>
		function buttonChange2(){
		
			document.getElementById("btn2").innerHTML= "New button Text!!!";
		}
	</script>
	
	
</body>


</html>